config/routes.rb
Rails.application.routes.draw do
  resources :rooms, only: [:index, :show]
  resources :guests, only: [:index, :show]
  resources :reservations, only: [:index, :show]
  resources :services, only: [:index, :show]
  
  root "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guests.rb
class Guests < ApplicationRecord
end

app/models/invoices.rb
class Invoices < ApplicationRecord
end

app/models/reservations.rb
class Reservations < ApplicationRecord
end

app/models/rooms.rb
class Rooms < ApplicationRecord
end

app/models/service_usages.rb
class ServiceUsages < ApplicationRecord
end

app/models/services.rb
class Services < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guests = Guests.all
  end

  def show
    @guest = Guests.find(params[:id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservations.all
  end

  def show
    @reservation = Reservations.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Rooms.all
  end

  def show
    @room = Rooms.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Services.all
  end

  def show
    @service = Services.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/guests/index.html.erb
<h1>Guests</h1>
<h2> Here are the Guest </h2>

<h4>
  <% @guests.each do |guest| %>
    <li>
        Guest <%= link_to guest.first_name, guest_path(guest) %>
        <%= link_to guest.last_name, guest_path(guest) %>
    </li>
  <% end %>

</h4>

<p> </p>
<%= link_to "Reservations", reservations_path %>
<%= link_to "Rooms", rooms_path %>
<%= link_to "Services", services_path %>

app/views/guests/show.html.erb
<h1><%= @guest.first_name %> <%= @guest.last_name %></h1>

<h4> - Email: <%= @guest.email %></h4>
<h4> - Phone: <%= @guest.phone %></h4>
<h4> - Document ID: <%= @guest.document_id %></h4>

<%= link_to "Back to Guest", guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lab 3" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<h1>Reservations</h1>
<h2> Here are the Reservations: </h2>

<h4>
  <% @reservations.each do |reservation| %>
    <li>
      Reservation <%= link_to reservation.code, reservation_path(reservation) %>    
    </li>
  <% end %>

</h4>

<p> </p>
<%= link_to "Guest", guests_path %>
<%= link_to "Rooms", rooms_path %>
<%= link_to "Services", services_path %>

app/views/reservations/show.html.erb
<h1>Reservation <%= @reservation.code %></h1>

<h2>The ID: </h2>
<h4> - Guest ID <%= @reservation.guest_id %></h4>
<h4> - Room ID <%= @reservation.room_id %></h4>
<p> </p>
<h2>The Checks: </h2>
<h4> - Check In <%= @reservation.check_in %></h4>
<h4> - Check Out <%= @reservation.check_out %></h4>
<p> </p>
<h2>The Status is <%= @reservation.status %></h2>
<p> </p>
<h2>Who stays: </h2>
<h4> - Adults <%= @reservation.adults %></h4>
<h4> - Children <%= @reservation.children %></h4>
<p> </p>
<%= link_to "Back to Reservations", reservations_path %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>

<h4>
  <% @rooms.each do |room| %>
    <li>
      <%= link_to room.number, room_path(room) %>
      - Type: <%= room.room_type %>
      - Price: $<%= room.price %>
      - Status: <%= room.status %>

    </li>    
  <% end %>
</h4>

<p> </p>
<%= link_to "Guest", guests_path %>
<%= link_to "Reservations", reservations_path %>
<%= link_to "Services", services_path %>

app/views/rooms/show.html.erb
<h1>Room <%= @room.number %></h1>

<p>Type: <%= @room.room_type %></p>
<p>Price: $<%= @room.price %></p>
<p>Status: <%= @room.status %></p>

<%= link_to "Back to Rooms", rooms_path %>

app/views/services/index.html.erb
<h1>Services</h1>
<h2> Here are the Reservations: </h2>

<h4>
  <% @services.each do |service| %>
    <li>
      Service of <%= link_to service.name, service_path(service) %> 
    </li>

  <% end %>

</h4>

<p> </p>
<%= link_to "Guest", guests_path %>
<%= link_to "Rooms", rooms_path %>
<%= link_to "Reservations", reservations_path %>

app/views/services/show.html.erb
<h1>Service <%= @service.name %></h1>

<h2>All the info </h2>

<h4> - The price is $<%= @service.price %></h4>
<h4> - Is active: <%= @service.is_active %></h4>

<%= link_to "Back to Services", services_path %>